{% set name = "repytah" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/repytah-{{ version }}.tar.gz
  sha256: 6a64e5068b042b7217e7e9d502ede011c40a274f727083257ebcefd262a56c1a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - numpy >=1.21.6
    - scipy >=1.7.3
    - pandas >=1.3.5
    - matplotlib-base >=3.3.4
    - opencv >=4.5.0
    - setuptools >=61.2.0

test:
  imports:
    - repytah
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/smith-tinkerlab/repytah
  summary: Python package for building Aligned Hierarchies for sequential data streams
  dev_url: https://github.com/smith-tinkerlab/repytah
  doc_url: https://repytah.readthedocs.io/
  license: ISC
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - kmkinnaird
